development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://myMaster/0
  # password: <%= ENV.fetch('REDIS_PASSWORD', nil) %>
  sentinels:
  - host: redis-sentinel
    port: 26379
  - host: redis-sentinel-additional
    port: 26379

